version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    # volumes: ['./:/usr/src/app']
    # image: app:1.0.0
    ports:
      - '80:3000'
    links:
      - mongo
  
  mongo:
    container_name: mongo
    # instead of building from Dockerfile,
    #image: will pull from dockerhub
    image: mongo
    ports:
      - '27017:27017'
